if(NOT PREFER_BUNDLED_LIBS)
  if(NOT CMAKE_CROSSCOMPILING)
    find_package(PkgConfig QUIET)
    pkg_check_modules(ZSTD libzstd)
  endif()
endif()

if(NOT ZSTD_FOUND)
  set(ZSTD_BUNDLED ON)
  set(ZSTD_SRC_DIR external/zstd)
  file(ZSTD_SRC GLOB_RECURSE "${ZSTD_SRC_DIR}/*.c" "${ZSTD_SRC_DIR}/*.h")

  set(ZSTD_DISABLE_ASM OFF)
  if(MSVC)
    set(ZSTD_DISABLE_ASM ON)
  else ()
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
      enable_language(ASM)
      set(ZSTD_SRC ${ZSTD_SRC} ${ZSTD_SRC_DIR}/decompress/huf_decompress_amd64.S)
    else()
      set(ZSTD_DISABLE_ASM ON)
    endif()
  endif()

  add_library(zstd EXCLUDE_FROM_ALL OBJECT ${ZSTD_SRC})
  set(ZSTD_INCLUDEDIR ${ZSTD_SRC_DIR})
  target_include_directories(zstd PRIVATE ${ZSTD_INCLUDEDIR})
  if(ZSTD_DISABLE_ASM)
    target_compile_definitions(zstd PRIVATE ZSTD_DISABLE_ASM)
  endif()

  set(ZSTD_DEP $<TARGET_OBJECTS:zstd>)
  set(ZSTD_INCLUDE_DIRS ${ZSTD_INCLUDEDIR})
  set(ZSTD_LIBRARIES)

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(ZSTD DEFAULT_MSG ZSTD_INCLUDEDIR)
endif()
